# Generated by Django 4.2.5 on 2023-10-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
