# Generated by Django 4.2.5 on 2023-10-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='minimum_cabinet_price',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='influencer',
            name='minimum_withdrawal_amount',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=7),
        ),
    ]
